# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 092e740eae046ee35c4322e8aca32b1501f09f80c1f41d6b224fc42b58382a09c432d868996e62ccf1be7f51340965bf38e50454739a3dc72a3e1849d20a49e6

test:
  secret_key_base: 2796d4cc5d816b0a5251d568b2e1085e54109c931cd705cd66050d4547c0dd4c252fe26cebacc8d3d6465be7286d519a19681a05bcdbd69084ea5bf7e7b1c875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
